//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/GameActionsAsset.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameActionsAsset"",
    ""maps"": [
        {
            ""name"": ""GameActionsMap"",
            ""id"": ""aa92654c-25b0-45f2-b2f8-e78e4ec50775"",
            ""actions"": [
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""3f68a4d5-8ed5-4630-8896-61cb7f3fb4af"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b44204cd-b30d-4973-81d2-18d59282a19e"",
                    ""path"": ""<Keyboard>/#(R)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameActionsMap
        m_GameActionsMap = asset.FindActionMap("GameActionsMap", throwIfNotFound: true);
        m_GameActionsMap_Restart = m_GameActionsMap.FindAction("Restart", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameActionsMap
    private readonly InputActionMap m_GameActionsMap;
    private IGameActionsMapActions m_GameActionsMapActionsCallbackInterface;
    private readonly InputAction m_GameActionsMap_Restart;
    public struct GameActionsMapActions
    {
        private @GameActions m_Wrapper;
        public GameActionsMapActions(@GameActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Restart => m_Wrapper.m_GameActionsMap_Restart;
        public InputActionMap Get() { return m_Wrapper.m_GameActionsMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActionsMapActions set) { return set.Get(); }
        public void SetCallbacks(IGameActionsMapActions instance)
        {
            if (m_Wrapper.m_GameActionsMapActionsCallbackInterface != null)
            {
                @Restart.started -= m_Wrapper.m_GameActionsMapActionsCallbackInterface.OnRestart;
                @Restart.performed -= m_Wrapper.m_GameActionsMapActionsCallbackInterface.OnRestart;
                @Restart.canceled -= m_Wrapper.m_GameActionsMapActionsCallbackInterface.OnRestart;
            }
            m_Wrapper.m_GameActionsMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Restart.started += instance.OnRestart;
                @Restart.performed += instance.OnRestart;
                @Restart.canceled += instance.OnRestart;
            }
        }
    }
    public GameActionsMapActions @GameActionsMap => new GameActionsMapActions(this);
    public interface IGameActionsMapActions
    {
        void OnRestart(InputAction.CallbackContext context);
    }
}
